name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
   
    steps:
    - name: Setup Python
      uses: actions/setup-python@v4.2.0
      with:
       python-version: '3.10' 
       
    - name: Checkout code
      uses: actions/checkout@v2      

    - name: Install Dependencies
      run: |
        pip install -r requirements.txt
        python manage.py runserver 0.0.0.0:8000
    
    
